name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check-out the repository source
        uses: actions/checkout@v2
      # Configure python
      - name: Setup python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      # Install pipenv
      - name: Pipenv configuration
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
      # Install dependencies of the repo
      - name: Install dependencies
        run: |
          python -m pipenv install
      # Run the project unit tests
      # Don't use pipenv shell: There's no shell to setup.
      - name: Run tests
        run: pipenv run python -m pytest
